### Handling Imbalaced Dataset

1. Up sampling
2. Down sampling

In [20]:
import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [21]:
n_class_0, n_class_1

(900, 100)

In [ ]:
## Creating dataframe with imbalanced dataset

class_0 = pd.DataFrame(
    {
        "feature_1": np.random.normal(loc=0, scale=1, size=n_class_0),
        "feature_2": np.random.normal(loc=0, scale=1, size=n_class_0),
        "target": [0] * n_class_0,
    }
)

class_1 = pd.DataFrame(
    {
        "feature_1": np.random.normal(loc=2, scale=1, size=n_class_1),
        "feature_2": np.random.normal(loc=2, scale=1, size=n_class_1),
        "target": [1] * n_class_1,
    }
)

In [39]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [40]:
df.head()

   feature_1  feature_2  target
0  -0.471276   0.328462       0
1   1.084072   1.038230       0
2  -0.379223   1.147064       0
3  -0.362274   0.638254       0
4  -0.681071  -1.075766       0

In [41]:
df.tail()

     feature_1  feature_2  target
995   2.720690   1.978489       1
996   1.949078   3.709793       1
997   2.709784   3.324917       1
998   1.817689   1.549237       1
999   2.838910   2.240773       1

In [ ]:
df["target"].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### Upsampling

In [ ]:
df_minority = df[df["target"] == 1]
df_majority = df[df["target"] == 0]

In [45]:
df_minority.shape

(100, 3)

In [ ]:
from sklearn.utils import resample

df_minority_upsampled = resample(
    df_minority,
    replace=True,  # sample with replcement
    n_samples=len(df_majority),
    random_state=42,
)

In [47]:
df_minority_upsampled.shape

(900, 3)

In [48]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   2.701255   0.056481       1
992   2.322342   3.289170       1
914   2.500618   1.338170       1
971   1.922944   2.907951       1
960   0.630218   0.982405       1

In [49]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [ ]:
df_upsampled["target"].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Downsampling

In [ ]:
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame(
    {
        "feature_1": np.random.normal(loc=0, scale=1, size=n_class_0),
        "feature_2": np.random.normal(loc=0, scale=1, size=n_class_0),
        "target": [0] * n_class_0,
    }
)

class_1 = pd.DataFrame(
    {
        "feature_1": np.random.normal(loc=2, scale=1, size=n_class_1),
        "feature_2": np.random.normal(loc=2, scale=1, size=n_class_1),
        "target": [1] * n_class_1,
    }
)

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Check the class distribution
print(df["target"].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
df_minority = df[df["target"] == 1]
df_majority = df[df["target"] == 0]

In [ ]:
from sklearn.utils import resample

df_majority_downsampled = resample(
    df_majority, replace=False, n_samples=len(df_minority), random_state=42
)

In [56]:
df_majority_downsampled.shape

(100, 3)

In [57]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [58]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64